### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by ivangudkov** [aidsoul/vktote#23]
Здравствуйте!

При запуске скрипта появляется такая ошибка: PHP Fatal error:  Uncaught Error: Class "Vktote\DataBase\DataBase" not found in /var/www/XXX/vktote/app/DataBase/Models/VkgroupModel.php:13.

Stack trace:
#0 /var/www/XXX/www/vktote/vendor/composer/ClassLoader.php(582): include()
#1 /var/www/XXX/www/vktote/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#2 /var/www/XXX/www/vktote/app/Telegram/Check.php(23): Composer\Autoload\ClassLoader->loadClass()
#3 /var/www/XXX/www/vktote/app/Telegram/Check.php(41): Vktote\Telegram\Check::checkIfExistGroup()
#4 /var/www/XXX/www/vktote/app/Telegram/Telegram.php(30): Vktote\Telegram\Check::checkIfExistPost()
#5 /var/www/XXX/www/vktote/app/Bot.php(28): Vktote\Telegram\Telegram->send()
#6 /var/www/XXX/www/vktote/groups/start.php(12): Vktote\Bot::start()
#7 {main}
  thrown in /var/XXX/data/www/vktote/app/DataBase/Models/VkgroupModel.php on line 13

Несколько раз переустанавливал на разных операционках (Debian 10, 11). Ошибка не пропадает. Сейчас стоит Debian 10, PHP 8.2.3 (cli).

Не могу разобраться в чем дело, помогите, пожалуйста.

**Comment by ivangudkov** [comment]
Проблема решена:

В папке /vktote/app/DataBase/ лежит файл Database.php - нужен DataBase.php. Переименование помогло.
